name: Gh-Pages

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: change base tag in html
        run: |
          ls
          sed -i 's,="/",="/fluttertest/",g' web/index.html
        working-directory: ./
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - uses: erickzanardo/flutter-gh-pages@v2
