name: Flutter CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: build, test, deploy web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # build APK (ADB also possible!)
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      # build for the web
      # credit: https://medium.com/flutter-community/flutter-web-github-actions-github-pages-dec8f308542a
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
        if: success() || failure()
      - run: flutter config --enable-web
        if: success() || failure()
      - run: flutter pub get
        if: success() || failure()
      - run: flutter build web --release
        if: success() || failure()
      - run: |
          cd build/web
          git init
          git config --global user.email valera.zuev.zva@gmail.com
          git config --global user.name zuevval
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/braille-systems/fluttertest.git
          git checkout -b gh-pages
          git add --all
          git commit -m "auto update"
          git push origin gh-pages -f
        if: success() || failure()
